#
# docker-compose --project-name web -f ./docker-compose.yml up --build
# ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -p 2222 admin@localhost
# 

version: '3.8'
services:
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
      args: 
        USER: ${DOCKER_USER}
        USER_GROUP: ${DOCKER_USER_GROUP}
        NODE_VARIANT: ${NODE_VARIANT}
    working_dir: /workdir
    environment:
      - NODE_ENV=${NODEJS_ENV}
    volumes:
      - ${LOCAL_WORKSPACE_DIR}:/home/${DOCKER_USER}/workspace
    secrets:
      - id_rsa
    ports:
      # - "3000:3000"
      # - "8000:8000"
      - "2222:22"
    command: ${SLEEP_CMD}


  # mongodb:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ../mongodb-data:/data/db
  #   ports:
  #     - "27017:27017"
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

secrets:
    id_rsa:
      file: ${SSH_PUB_KEY}